package com.sphereon.crypto.kms

import com.sphereon.crypto.generic.KeyType
import com.sphereon.crypto.kms.model.IdentifierMethod
import com.sphereon.kmp.Uuid

/**
 * Abstract base class for key resolver services.
 *
 * This class provides common functionality for resolving cryptographic keys.
 *
 * @property id Unique identifier for the service instance, generated by default.
 * @property supported A map that associates identifier methods with arrays of supported key types.
 */
abstract class AbstractKeyResolverService(
    private val id: String = Uuid.v4String(),
    private val supported: Map<IdentifierMethod, Array<KeyType>>
) : IKeyResolverService {

    override fun getId() = id
    override fun allSupportedIdentifierMethods(): Array<IdentifierMethod> = supported.keys.toTypedArray()
    override fun allSupportedKeyTypes(): Array<KeyType> = supported.flatMap { it.value.toSet() }.toSet().toTypedArray()
    override fun supportedKeyTypesAndIdentifierMethods(): Map<IdentifierMethod, Array<KeyType>> = supported

    override fun getSupportedKeyTypes(identifierMethod: IdentifierMethod): Array<KeyType> = supported[identifierMethod] ?: emptyArray()

    override fun getSupportedIdentifierMethods(keyType: KeyType): Array<IdentifierMethod> =
        supported.filter { it.value.contains(keyType) }.keys.toTypedArray()

}
